#+TITLE: Project development

* What is this?

This document will have all the plans and documentation for the project.

Using Emacs with Org mode strongly advised.

* TODO Running the project
** Create a .env file

Copy the example /.env/ file

#+begin_src shell
cp .env.example .env
#+end_src

It should look like this:

#+begin_src conf
APP_NAME=Chan
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost
APP_TIMEZONE=UTC

LOG_CHANNEL=stack
LOG_SLACK_WEBHOOK_URL=

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=chan
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=file
QUEUE_CONNECTION=sync
#+end_src

Setup your database connection by setting the /DB_/ fields appropriately.

Example with postgresql:

#+begin_src conf
APP_NAME=Chan
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost
APP_TIMEZONE=UTC

LOG_CHANNEL=stack
LOG_SLACK_WEBHOOK_URL=

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=chan
DB_USERNAME=your_user
DB_PASSWORD=your_password

CACHE_DRIVER=file
QUEUE_CONNECTION=sync
#+end_src

** Run migrations

#+begin_src shell
php artisan migrate:fresh
#+end_src

*Optional* run seeders

#+begin_src shell
php artisan db:seed
#+end_src

** Run the server

#+begin_src shell
php -S localhost:8000 -t public
#+end_src


* Project minimum

Here we will go over the minimum working functionality expected in the *next* master branch merge.
You can read *next* as *current* if you're reading this in the master branch.
Read this document on develop branch for upcoming changes.

Basically everything will be described here.

** Boards
*** Base model

    | attribute   | type   | example                              | extra   |
    |-------------+--------+--------------------------------------+---------|
    | id          | uuidv4 | eb6f2aa2-b9a7-4239-a89c-8d2cef484dae |         |
    | name        | text   | technology                           | unique  |
    | shorthand   | text   | t                                    | unique  |
    | description | text   | /t/ - Technology                     | virtual |

In json format:

#+begin_src json
{
    "id": "eb6f2aa2-b9a7-4239-a89c-8d2cef484dae",
    "name": "technology",
    "shorthand": "t",
    "description": "/t/ - Technology"
}
#+end_src

*** Endpoints
**** List all boards

Request format:

#+begin_src http
GET localhost:8000/boards/
Accept: application/json
#+end_src

#+RESULTS:
#+begin_example
HTTP/1.1 200 OK
Host: localhost:8000
Date: Wed, 05 Jan 2022 16:54:50 GMT
Connection: close
X-Powered-By: PHP/8.0.14
Cache-Control: no-cache, private
Date: Wed, 05 Jan 2022 16:54:50 GMT
Content-Type: application/json

[{"id":"c0849eda-be50-4c4e-8249-ddba738d776e","name":"Technology","shorthand":"g","description":"\/g\/ - Technology"}]
#+end_example

Example response json:

#+begin_src json
[
    {
        "id": "eb6f2aa2-b9a7-4239-a89c-8d2cef484dae",
        "name": "technology",
        "shorthand": "t",
        "description": "/t/ - Technology"
    },
    {
        "id": "7510a583-ba79-4796-a7c0-6866319e9e87",
        "name": "video games",
        "shorthand": "vg",
        "description": "/vg/ - Video games"
    },
]
#+end_src
