openapi: 3.0.0
info:
  title: 'Link Example'
  version: 1.0.0
paths:
  /boards:
    get:
      tags:
        - boards
      operationId: getBoards
      responses:
        '200':
          description: 'List of Boards'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/board'
  '/boards/{board_id}':
    get:
      tags:
        - boards
      operationId: getBoardById
      parameters:
        -
          name: board_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'Single Board'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board'
        '404':
          description: 'Not Found'
        '400':
          description: 'Invalid uuid'
components:
  schemas:
    board:
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: 0bb3abb9-986c-47a3-9a1c-c61e67d506f2
        name:
          type: string
          example: Technology
        shorthand:
          type: string
          example: g
        description:
          type: string
          readOnly: true
          example: '/g/ - Technology'
      type: object
